version = 5.8.0
archive_dir = /config/etc/letsencrypt/archive/miorii.kitek-pg.ru
cert = /config/etc/letsencrypt/live/miorii.kitek-pg.ru/cert.pem
privkey = /config/etc/letsencrypt/live/miorii.kitek-pg.ru/privkey.pem
chain = /config/etc/letsencrypt/live/miorii.kitek-pg.ru/chain.pem
fullchain = /config/etc/letsencrypt/live/miorii.kitek-pg.ru/fullchain.pem
[renewalparams]
account = 3710f9a2a2b368cde6b818b8b52d5717
pref_challs = http-01,
config_dir = /config/etc/letsencrypt
work_dir = /tmp/letsencrypt
logs_dir = /config/log/letsencrypt
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = standalone
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-09-29T18:09:51
